### ISSUE TITLE
Make `kern/panic.c` not depend on any other files.

### ISSUE THREAD

**Issue by omnit3a** [kaneru-os/kaneru#15]
If there was a kernel panic, it is highly possible that no other files were able to be loaded. If this is the case, then there is no way for a kernel panic to print out any debug information, as the files containing the code for printing that information might not have been loaded.
I suggest either reworking the panic code, or making a copy of the text printing code inside of `kern/panic.c`.

**Comment by untodesu** [comment]
That's the thing about having multiple `klog_sink_t` instances registered: if something blows up inbetween, at least one is going to be available.

The suggestion is valid though, but I'd rather name it as "Register arch-specific early klog sinks before everything else"

**Comment by untodesu** [comment]
Felting things up
