### ISSUE TITLE
Capability to detect whether or not a terminal has colour capabilites

### ISSUE THREAD

**Issue by omnit3a** [kaneru-os/kaneru#5]
## Description
I believe that this would be important for maintaining compatibility with old serial terminals with no colour support, as I'm pretty sure that they would just spit out garbage on the screen upon encountering an invalid escape sequence (i.e. colour escape sequences).

## Implementation
This would probably be best to do by having a struct that contains the properties of any terminal which may be connected to an IO port.
This could include:
- Colour support
- Baud rate
- Screen size (x/y)

**Comment by untodesu** [comment]
So basically `terminfo` and `termios`, right?

**Comment by untodesu** [comment]
The kernel itself shouldn't care about color support in all its `console_t` objects: escape sequences are a standard and as far as I know sending invalid sequences shouldn't make a terminal explode.  

Although for unprivileged (userland :trollface:) code (say, ncurses) having a `terminfo` library should be a must...
